return {
	"nvim-neorg/neorg",
	lazy = false, -- Disable lazy loading as some `lazy.nvim` distributions set `lazy = true` by default
	version = "*", -- Pin Neorg to the latest stable release
	config = true,
}
--{
--	"nvim-neorg/neorg",
--	build = ":Neorg sync-parsers",
--	dependencies = {
--		"nvim-lua/plenary.nvim",
--		"nvim-treesitter/nvim-treesitter",
--		"nvim-treesitter/nvim-treesitter-textobjects",
--		"nvim-cmp",
--		"hrsh7th/nvim-cmp", -- For completion
--		-- Optional dependencies
--		"nvim-neorg/neorg-telescope", -- For Telescope integration
--		"pysan3/neorg-templates", -- For templates
--		"nvim-neorg/neorg-contexts", -- For GTD contexts
--	},
--	opts = {
--		load = {
--			["core.defaults"] = {}, -- Loads default behaviour
--			["core.concealer"] = { -- Adds pretty icons to your documents
--				config = {
--					icon_preset = "diamond",
--					icons = {
--						code_block = {
--							enabled = true,
--						},
--						heading = {
--							enabled = true,
--							level_1 = {
--								enabled = true,
--							},
--						},
--					},
--				},
--			},
--			["core.completion"] = { -- Enables completion
--				config = {
--					engine = "nvim-cmp",
--					name = "[Neorg]",
--				},
--			},
--			["core.dirman"] = { -- Manages Neorg workspaces
--				config = {
--					workspaces = {
--						notes = "~/notes",
--						work = "~/notes/work",
--						personal = "~/notes/personal",
--						journal = "~/notes/journal",
--					},
--					default_workspace = "notes",
--				},
--			},
--			["core.summary"] = {}, -- Enables table of contents
--			["core.export"] = {}, -- Enables export functionality
--			["core.export.markdown"] = {}, -- Enables Markdown export
--			["core.presenter"] = { -- For presentations
--				config = {
--					zen_mode = "zen-mode",
--				},
--			},
--			["core.ui.calendar"] = {}, -- Calendar integration
--			["core.keybinds"] = { -- Configures keybinds
--				config = {
--					default_keybinds = true,
--					neorg_leader = "<Leader>n",
--					hook = function(keybinds)
--						-- Custom keybinds
--						keybinds.map("norg", "n", "<leader>nn", ":Neorg workspace notes<CR>")
--						keybinds.map("norg", "n", "<leader>nj", ":Neorg workspace journal<CR>")
--						keybinds.map("norg", "n", "<leader>nw", ":Neorg workspace work<CR>")
--						keybinds.map("norg", "n", "<leader>np", ":Neorg workspace personal<CR>")
--
--						-- GTD specific keybinds
--						keybinds.map("norg", "n", "<leader>nt", ":Neorg gtd views<CR>")
--						keybinds.map("norg", "n", "<leader>nc", ":Neorg gtd capture<CR>")
--
--						-- Export keybinds
--						keybinds.map("norg", "n", "<leader>ne", ":Neorg export to-file<CR>")
--					end,
--				},
--			},
--			["core.integrations.telescope"] = {}, -- Telescope integration
--			["core.journal"] = { -- Journaling support
--				config = {
--					strategy = "flat",
--					workspace = "journal",
--				},
--			},
--			["core.gtd.base"] = { -- GTD support
--				config = {
--					workspace = "gtd",
--					projects = {
--						show_completed_projects = true,
--						show_projects_without_tasks = true,
--					},
--					contexts = {
--						show_context_next = true,
--						show_context_projects = true,
--					},
--					custom_tag_completion = true,
--				},
--			},
--			["core.esupports.metagen"] = { -- Metadata generation
--				config = {
--					type = "auto",
--				},
--			},
--			["external.templates"] = {}, -- Template support
--			["external.context"] = {}, -- GTD contexts
--		},
--	},
--	keys = {
--		-- Quick workspace switching
--		{ "<leader>nn", ":Neorg workspace notes<CR>", desc = "Switch to notes workspace" },
--		{ "<leader>nj", ":Neorg workspace journal<CR>", desc = "Switch to journal workspace" },
--		{ "<leader>nw", ":Neorg workspace work<CR>", desc = "Switch to work workspace" },
--		{ "<leader>np", ":Neorg workspace personal<CR>", desc = "Switch to personal workspace" },
--
--		-- Common actions
--		{ "<leader>ni", ":Neorg index<CR>", desc = "Open index" },
--		{ "<leader>nr", ":Neorg return<CR>", desc = "Return to last workspace" },
--		{ "<leader>nt", ":Neorg toggle-concealer<CR>", desc = "Toggle concealer" },
--
--		-- GTD
--		{ "<leader>ng", ":Neorg gtd views<CR>", desc = "Open GTD views" },
--		{ "<leader>nc", ":Neorg gtd capture<CR>", desc = "GTD capture" },
--
--		-- Journal
--		{ "<leader>nj", ":Neorg journal today<CR>", desc = "Open today's journal" },
--	},
--}
