vim.cmd("let g:netrw_liststyle = 3")

local o = vim.opt
local fn = vim.fn
local wo = vim.wo

o.background = dark
o.backspace = "indent,eol,start" -- Allow backspace over everything in insert mode
o.clipboard = "unnamed" -- Allows neovim to access the system clipboard
o.cmdheight = 1 -- Space for displaying messages/commands
o.completeopt = { "menu", "menuone", "noselect", "noinsert" } -- A comma separated list of options for Insert mode completion
o.conceallevel = 2 -- Dont hide symbols in MD and JSON
o.encoding = "UTF-8" -- Set global encoding to UTF-8
o.expandtab = true -- Convert tabs to spaces
o.foldenable = true -- Enable folding globally
o.foldmethod = "syntax" -- Use syntax-based folding by default
o.foldlevel = 99 -- Start with all folds open
o.hidden = true -- Opening a new file when current buffer has unsaved changes causes files to be hidden instead of closed
o.history = 500 -- Sets the number of lines that command mode remembers
o.hlsearch = true -- Highlight all matches on previous search pattern
o.ignorecase = true -- Ignore case in search patterns
o.incsearch = true -- Incremental search
--o.lazyredraw     = true -- Do not redraw screen while running macros
o.listchars = "tab:..,trail:_,extends:>,precedes:<,nbsp:~,eol:$,space:_" -- Define whitespace characters
o.mouse = "n" -- Set mouse mode for terminal window resizing
o.number = true -- Set line number
o.relativenumber = true
o.scrolloff = 8 -- Minimum number of screen lines to keep above and below the cursor.
o.shiftwidth = 2 -- The number of spaces inserted for each indentation
o.shortmess = o.shortmess + "T" -- Prevent "pattern not found" messages
o.showmode = false -- Hide statusline info
o.showtabline = 2 -- Always show tabs
o.sidescrolloff = 5 -- The minimal number of columns to scroll horizontally
o.signcolumn = "yes"
o.smartcase = true -- Smart case
o.smartindent = true -- Make indenting smart again
o.splitbelow = true -- Force all horizontal splits to go below current window
o.splitright = true -- Force all vertical splits to go to the right of current window
o.swapfile = false -- Disable .swp files
o.tabstop = 4 -- How many columns a tab counts for
o.termguicolors = true -- Set term gui colors
o.title = true -- Show filename in titlebar of window
o.undofile = true -- Enable persistent undo
o.wildignorecase = true -- When set case is ignored when completing file names and directories
o.wildmenu = true -- Enhanced command-line completion
o.wildmode = "longest:full" -- Complete till longest common string + 'wildmenu' if it is enabled.
o.wrap = false
wo.cursorline = true -- Highlight the current line
